### ISSUE TITLE
Problems aligning certain Japanese characters with Whisper engine

### ISSUE THREAD

**Issue by fechan** [echogarden-project/echogarden#35]
I'm trying to do forced alignment with a Japaense transcript and corresponding audio using the Whisper engine, but it keeps raising errors like the following:

```
Prepare for alignment.. 153.9ms
Load alignment module.. 0.7ms
Load tokenizer data.. 289.2ms
Create ONNX inference session for model 'tiny'.. 8657.4ms
Prepare for alignment.. Error: Failed tokenizing the given text. The word ' 遅刻' contains a subword '遅' which is not in the vocabulary.
```

I am using the following command:
```
echogarden align audio.wav transcript.txt --language=ja --engine=whisper --whisper.model=medium --plainText.paragraphBreaks=double
```

If I transcribe `遅刻` into hiragana `ちこく`, it will align this just fine. However, not all hiragana will work, like `ぱ`:

```
Prepare for alignment.. Error: Failed tokenizing the given text. The word ' ぱん' contains a subword 'ぱ' which is not in the vocabulary.
```

Various other Japanese characters break, including katakana `ヨ` and certain fullwidth punctuation like `？`, but other katakana and punctuation seem to work (including `ハ` and `…`).

**Comment by rotemdan** [comment]
Thanks for the report.

The Whisper tokenization is based on a pure JavaScript implementation I made myself, and uses a standard GPT2 tokenizer.

This isn't exactly what is used on the official Whisper implementation, but originally I had no choice but to implement it myself. 

The encoding part of the tokenizer, especially, is mostly intended to tokenize outputs of Whisper itself, for the purpose of prompting the model for continuations between recognized segments.

The Whisper-based alignment feature is very experimental and only supports up to 30 seconds of audio.

This means that the tokenizer can't necessarily encode all text and all types of characters, even within Whisper's 99 supported languages, in a robust way, and that is not a well-tested feature since it is not commonly used aside from this particular form of experimental alignment method.

Anyway, since I wrote the original tokenizer, it seems like there are now better tokenizers available in JavaScript, like the newer [`tiktoken` package](https://www.npmjs.com/package/tiktoken), which is based on a the official OpenAI tokenizers written in Python, and that is seems used internally in the current Whisper Python implementation (that wasn't originally the case in the original September 2022 release).

I could switch to use this package instead in the future.

In any case, just know that Japanese support is bad, in general, for alignment within Echogarden, since the `espeak` library - which is heavily used internally, doesn't understand many types of Japanese characters. This is a known problem in `espeak` and there isn't much I can do about it. (I believe the problem has something to do with "Kanji" characters, but I'm not sure if that's the entirety of it).

**Comment by fechan** [comment]
In the meantime I've decided to use [WhisperX](https://github.com/m-bain/whisperX) directly, which is a variation on Whisper that does ASR and alignment at the word/subword level.

I don't know how relevant my workflow is to the echogarden project, since it's pretty specific to Japanese, but I'll document it here just in case:

For my purposes I have a list of sentences which are timed to some audio, and I provide the timed sentences and the audio to WhisperX's alignment function and it returns timings for each character in my text (in the case of Japanese).

This is more granular than I want, so to get timings for morphemes I tokenize my text with MeCab and figure out which characters correspond to each MeCab token.

**Comment by rotemdan** [comment]
In the newly release `1.0.0` version, I've integrated the `tiktoken` tokenizer. It can deal with many more types of characters, including some very obscure emojis. 

I also fixed several tokenization issues related to Chinese characters, and other characters that require multiple tokens.

It's possible that the issue you described is resolved in the new version (it would be great to have a sample), although the limitations of `eSpeak` with Japanese "Kanji" characters still exist, and are not likely to be resolved any time soon, unfortunately, since that is beyond my control.

If you're only looking for trying Japanese speech recognition, it's possible the new version could be useful again (it's now seems to be working fine with Chinese, also providing some level of word segmentation - though that still need work).

Also there's now support for `whisper.cpp`, that supports large models and GPU processing. Providing a much faster alternative than the integrated Whisper port I developed (which has been enhanced a lot since but still has no large model or GPU support due to the current limitations of `onnruntime-node` - though they plan to provide these features later this year).
