### ISSUE TITLE
Some issues when using echogarden in an Electron app

### ISSUE THREAD

**Issue by an-lee** [echogarden-project/echogarden#44]
First of all, thank you for this fantastic package!

I'm currently integrating echogarden into an Electron application, which relies on ffmpeg as well. To manage ffmpeg's binaries, I'm utilizing [ffmpeg-static](https://github.com/eugeneware/ffmpeg-static), enabling its inclusion in the user's download of the app.

Despite this, echogarden insists on downloading its own ffmpeg binary—except on macOS.

Here's the crux of the issue:
1. Windows and Linux users are forced to download an additional ffmpeg binary, even though one is already bundled with the application.
2. For macOS users, although the ffmpeg binary is bundled, echogarden repeatedly issues a warning that `it cannot find the ffmpeg utility`. Given that it's a desktop app, we can't presume that users have ffmpeg installed, and most wouldn't know how to install it, hence why we bundle it with the app.

A couple of potential solutions spring to mind:
1. If echogarden could integrate with [ffmpeg-static](https://github.com/eugeneware/ffmpeg-static), it would gracefully resolve my issue.
2. Alternatively, providing a configuration option within echogarden for specifying the ffmpeg binary path could be very helpful.

I really appreciate all the effort that's gone into making such an exceptional package! Thank you once again!

**Comment by an-lee** [comment]
I also attempted to fork the repository, make a few adjustments(https://github.com/an-lee/echogarden/commit/b0d42e73b29486f97fd49e10b6f6eca83253d98b), and then utilize it in my project. 

However, I’m not sure how to compile it. It seems including the module directly from `/src` does not work.

**Comment by rotemdan** [comment]
Echogarden has an internal package download system written fully in TypeScript. No shell scripts involved. This system was originally intended for download various models, like speech synthesis and recognition models.

These packages are stored as `.tar.gz` files and downloaded from here:

https://huggingface.co/echogarden/echogarden-packages/tree/main

Given all the work that went into developing this system, I'm currently using it also to download the FFMpeg and SoX binaries, although that's not its original intention.

The reason I decided to download the SoX binaries from there, is because commonly available version (latest) are broken for what Echogarden does, in particular version `14.4.2` is completely broken on Windows.

Also, several SoX versions that was tried on macOS is apparently broken when it comes to playback via stdin, so I have to write temporary `.wav` files to disk before playback, which is something I wish I could fix, since these files just add up and consume space. I discovered this issue only via a user on this issue tracker. I couldn't observe or try to fix it myself without access to a mac. Maybe if I had access I could have solved it.

The reason it downloads FFMpeg is simply to ensure a particular version and make things more reliable and reproducible. Otherwise I may get all sort of odd compatibility issues caused by people having different versions in their system, that I can't handle. 

The reason the download is currently forced is because this was originally intended as a command-line application, not as a package! That only came later. I preferred not to require the user to keep adding CLI options like `--use-internal-ffmpeg`, or `--use-local-ffmpeg`. This was simply a choice to make things easier for the user. I can change this any time.

The reason it doesn't download binaries on macOS, again, is simply because I have *no access* to a macOS system so I couldn't find a version of these binaries that is properly signed! The version that was downloaded before showed signature errors, so I disabled the download.

Anyway, the package you are suggesting, like `ffmpeg-static`, is not going to provide any significant benefit over using the internal downloader. There's simply no reason to use it, since the downloader I wrote is something I have control over, and that integrates better with the application. Also, I already have a dedicated repository for the download, so I'm not downloading from third-party URL that may become broken in the future.

I could imitate some of the logic that `ffmpeg-static` uses internally to detect various platforms, and use the same binaries it downloads on macOS. But.. again I can't test it on macOS, so I wouldn't know if it works correctly. I can just "guess".

Anyway, these are not major or special issues with the main functionality Echogarden and they can be easily resolved. It's just that as I said, it was originally made a command-line tool, and use as a package was secondary, and macOS support could have been better if I could test it myself on that platform.

To compile it only requires TypeScript: simply run `tsc .` in the root directory. There are no special build scripts (intentional made very simple). 

You can use this `tasks.json` file if you're using VSCode to have it auto-compile:
```json
{
	"version": "2.0.0",
	"command": "tsc.cmd",
	"args": [
		"-w",
		"-p",
		"."
	],
	"problemMatcher": "$tsc-watch",
	"isBackground": true,
	"tasks": [
		{
			"label": "node",
			"type": "shell",
			"command": "tsc",
			"args": [
				"-w",
				"-p",
				"."
			],
			"isBackground": true,
			"problemMatcher": "$tsc-watch",
			"group": {
				"kind": "build",
				"isDefault": true
			},
		}
	]
}
```

**Comment by an-lee** [comment]
Thank you for your gracious response. I completely understand the rationale behind echogarden's design choices.

I’ve managed to compile echogarden successfully with the guidance you provided. I’ll now go ahead and modify my fork slightly to better align with my project's requirements.

Additionally, I'd like to suggest the possibility of allowing users to specify a custom path for ffmpeg/sox. I can appreciate your preference for maintaining simplicity in the design. Perhaps implementing an environment variable could serve as the simplest form of configuration. For instance:

```javascript
if (process.env.FFMPEG_PATH) return process.env.FFMPEG_PATH;
```

Many thanks again.

**Comment by rotemdan** [comment]
Sure, I'll add a custom path, but most likely not through an environment variable! Because that's not platform independent, it's difficult to customize, easy to get forget or wrong, can't be specialized for multiple instances or multiple threads, doesn't match the current API. Etc!

More likely, I'll add some sort of global setting for the API. I also need to add a similar global setting to set the verbosity level, and maybe some other options.

Maybe some sort of global object like:

```ts
Echogarden.globalOptions.ffmpegPath = ' ... '
Echogarden.globalOptions.soxPath = ' ... '
Echogarden.globalOptions.verbosity = 'silent'
```

This setting will be naturally thread-local, so I need to provide a way to set it when a worker is running in a separate thread. It's not obvious to me how to do it right now, I'll need to look into it.

For the command-line app, I'll need to see how to add global options in a way that is easy to manage. That's a part of the reason it hasn't been added so far. Currently almost all options are operation-specific.

Also, I really want to have the auto-downloaded binaries work for macOS, at least for FFMpeg, so I'll look into the binaries in `ffmpeg-static`, though again, I have no way to test them on Mac, so I'll need to get feedback from someone else.

**Comment by an-lee** [comment]
> More likely, I'll add some sort of global setting for the API. I also need to add a similar global setting to set the verbosity level, and maybe some other options.

Sounds fantastic! I'm looking forward to seeing it happen.

> Also, I really want to have the auto-downloaded binaries work for macOS, at least for FFMpeg, so I'll look into the binaries in `ffmpeg-static`, though again, I have no way to test them on Mac, so I'll need to get feedback from someone else.

I have test machines for both x64 mac and arm64 mac. I'll would like to help for testing. Just ping me when it's ready!

**Comment by rotemdan** [comment]
The builds `ffmpeg-static` use for macOS are sourced from:

https://osxexperts.net/
https://evermeet.cx/pub/ffmpeg/

ossexperts.net includes the following notice about code signing.

```
For macOS 10.15 or higher you need to remove the file from quarantine.
You can do this in the Terminal:
xattr -dr com.apple.quarantine <pathtotheffmpegfile>

Apple Silicon devices can only run signed files.
If needed you can ad-hoc sign the downloaded file in the Terminal:
xattr -cr <pathtotheffmpegfile>
codesign -s - <pathtotheffmpegfile>
```

After looking at the source code, I found out they actually download their builds from this GitHub release:

https://github.com/eugeneware/ffmpeg-static/releases/tag/b6.0

I'm just not 100% sure if the macOS builds are somehow pre-signed. I don't know how that works and there is no information or issue on the repository on whether these binaries are getting quarantined.

Can you help me test whether these builds are not getting quarantined:

x64:
https://github.com/eugeneware/ffmpeg-static/releases/download/b6.0/ffmpeg-darwin-x64.gz

arm64:
https://github.com/eugeneware/ffmpeg-static/releases/download/b6.0/ffmpeg-darwin-arm64.gz

Otherwise there is no way for me to know.

Once I know they are usable, I will upload them to Hugging Face repository to be downloaded on-demand.

**Comment by an-lee** [comment]
> x64:
> https://github.com/eugeneware/ffmpeg-static/releases/download/b6.0/ffmpeg-darwin-x64.gz
>
> arm64:
> https://github.com/eugeneware/ffmpeg-static/releases/download/b6.0/ffmpeg-darwin-arm64.gz

I think they are not quarantined and good to run. 

The result are as following. arm64 version is also tested, the result is similar, no quarantine.

```bash
➜  Downloads gzip -dk ./ffmpeg-darwin-x64.gz 
➜  Downloads chmod +x ./ffmpeg-darwin-x64
➜  Downloads ./ffmpeg-darwin-x64
ffmpeg version 6.0-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

**Comment by rotemdan** [comment]
I uploaded all the builds from `ffmpeg-static` to the Hugging Face repository.

I also added a global option for a custom ffmpeg path (using the new methods `getGlobalOption` and `setGlobalOption`), and changed the resolution logic to prioritize any existing version on system path.

Here is how the logic works now:

```ts
async function getFFMpegExecutablePath() {
	// If a global option set for the path, use it
	if (getGlobalOption('ffmpegPath')) {
		return getGlobalOption('ffmpegPath')
	}

	// If an 'ffmpeg' command exist in system path, use it
	if (await commandExists('ffmpeg')) {
		return 'ffmpeg'
	}

	// Otherwise, download and use an internal ffmpeg package
	const platform = process.platform
	const arch = process.arch

	let packageName: string

	if (platform === 'win32' && arch === 'x64') {
		packageName = 'ffmpeg-6.0-win32-x64'
	} else if (platform === 'win32' && arch === 'ia32') {
		packageName = 'ffmpeg-6.0-win32-ia32'
	} else if (platform === 'darwin' && arch === 'x64') {
		packageName = 'ffmpeg-6.0-darwin-x64'
	} else if (platform === 'darwin' && arch === 'arm64') {
		packageName = 'ffmpeg-6.0-darwin-arm64'
	} else if (platform === 'linux' && arch === 'x64') {
		packageName = 'ffmpeg-6.0-linux-x64'
	} else if (platform === 'linux' && arch === 'ia32') {
		packageName = 'ffmpeg-6.0-linux-ia32'
	} else if (platform === 'linux' && arch === 'arm64') {
		packageName = 'ffmpeg-6.0-linux-arm64'
	} else if (platform === 'linux' && arch === 'arm') {
		packageName = 'ffmpeg-6.0-linux-arm'
	} else if (platform === 'freebsd' && arch === 'x64') {
		packageName = 'ffmpeg-6.0-freebsd-x64'
	} else {
		return undefined
	}

	const ffmpegPackagePath = await loadPackage(packageName)

	let filename = packageName

	if (platform === 'win32') {
		filename += '.exe'
	}

	return path.join(ffmpegPackagePath, filename)
}
```

I'll release the updated version soon. Just need to test a little bit more to ensure everything is okay.

**Comment by rotemdan** [comment]
I published version `0.12.0` with the updated ffmpeg packages and executable resolution approach.

There are several other changes, like 13 new VITS voices, and the new global options method `setGlobalOption`, `getGlobalOption`.

Please let me know if there are any issues.

---

Also, if the ffmpeg builds work correctly on macOS, it would be great to also find signed SoX binaries for macOS x64 and ARM64. I can't do this without access to a mac, though. I tried really hard to find a way to extract it from the Homebrew's Docker images - but it turned out to be nearly impossible to get hold of it in that way.

If you have knowledge of how to locate and copy the exact binaries used by Homebrew. In particular the binaries associated with the "formula" described on this URL:

https://formulae.brew.sh/formula/sox

Then it would be great, hoping it is pre-signed. I could add it in an update.

**Comment by an-lee** [comment]
> I published version `0.12.0` with the updated ffmpeg packages and executable resolution approach.
> 
> There are several other changes, like 13 new VITS voices, and the new global options methods `setGlobalOption` and `getGlobalOption`.
> 
> Please let me know if there are any issues.
> 

It works just well! Thanks!


> If you have knowledge of how to locate and copy the exact binaries used by Homebrew. In particular the binaries associated with the "formula" described on this URL:
> 
> https://formulae.brew.sh/formula/sox

I'll give it a shot.

**Comment by an-lee** [comment]
I've tried to extract the SoX binary, but I've never been successful. I apologize.

Since the issue regarding echogarden in the Electron App has been resolved, I'm going to close it.

**Comment by rotemdan** [comment]
Thanks for the effort and all the feedback!

Maybe in the future we'll be able to add a pre-signed SoX binary. I appreciate your help.
