### ISSUE TITLE
Issues with Importing Echogarden

### ISSUE THREAD

**Issue by ncioffi1** [echogarden-project/echogarden#46]
Hey.  So:

When I try to npm install echogarden, and then run my node project, I get

ERROR in ./src/App.js 6:0-41
Module not found: Error: Cannot find file: 'API.js' does not match the corresponding name on disk: './node_modules/echogarden/dist/API/api'.

Can't quite figure out why it doesn't npm install right / what exactly I'm missing in the setup process.

**Comment by rotemdan** [comment]
I've made a minimal test code to ensure the API loads correctly:

I created a new directotry.

I ran `npm install echogarden`

Then added `"type": "module"`, like:
`package.json`:
```
{
  "type": "module",
  "dependencies": {
    "echogarden": "^0.12.2"
  }
}
```

Now made this test file:
`test.js`:
```js
import * as Echogarden from 'echogarden'

const result = await Echogarden.synthesize("Hello world")

console.log(result)
```

That worked (Windows 11), so it doesn't seem so recent update broke anything.

Try to see what about your setup is different? Have you set `"type": "module"`? Maybe you're trying to load the library in a different way?

**Comment by ncioffi1** [comment]
Huh.  Looks like that worked.  

My initial issue was from trying to install this / deploy this as part of a React project... I'll see if I can build off this and make it work.

Thank you for the quick reply!

**Comment by ncioffi1** [comment]
Hmm...

Just wondering if there's a specific way in which I'm supposed to build a given WebSocket server?

I'm able to get a WebSocket setup to work with my local machine, but when I try deploying it on a service like Render / installing it that way, I encounter errors.

To be clear, the 'echogarden serve' command line bit works fine - I am able to build a server that handles incoming requests.

The problem arises when trying to build an echogarden **client** that receives these requests.  I built out a makeshift API that handles what I want to do, but when I try to deploy and do things with the echogarden.client, I run into trouble.  This works on my local machine, but when I deploy, I still encounter issues when handling scripts that import 'echogarden', and haven't been able to find a workaround.

So, I've isolated the issue down to:  

```

import * as Echogarden from 'echogarden'

```

Any time I try to deploy & run code with this statement in it, I encounter this:

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/opt/render/project/src/node_modules/echogarden/' imported from /opt/render/project/src/server.js

Am actively looking at workarounds for the problem, and am wondering:
1.  Are there any additional setup steps required outside of the above in order to install this package and make it work on an express.js app? 
2.  Is it possible to interface with the WebSocket server without doing echogarden.client / without importing echogarden?  How data intensive are the client commands?  

Any insight would be greatly appreciated, this has been a real head scratcher on my end.  Thanks for reading and sorry for the trouble.

**Comment by rotemdan** [comment]
I couldn't fully understand what the exact issue is, from what you described.

If there are issues importing the package on a remote server, then they are not specific to the server component. They could be related to, maybe, the `node.js` version used. An error like `Cannot find package '/opt/render/project/src/node_modules/echogarden/'` could happen because the `echogarden` package failed to install. It's hard to know based on this limited information.

The server and client modules have not been thoroughly tested, though I am continuously testing the server locally on my PC (for several months now).

However, the client module `Echogarden.Client` has received almost no testing at all. I wrote it to ensure it exists and moved on to other things. Also, there's really not reason to have it embedded in the full package, since it has almost no dependencies. It should be separated to a different package. The goal is to have it as lightweight and portable as possible. Also, it should work inside a web browser, of course, which means it must be separated anway. 

All of that is on the TODO list. Currently, the amount of effort I can put to this project isn't very large. I didn't assume many people want to use the client / server right away. Also because the message protocol isn't fully finalized, and currently missing some operations.

So maybe let's first try to identify and resolve the issues with importing the package, then I'll try to prioritize the work on making the client module more independent and usable.

**Comment by JunDev76** [comment]
I solved this problem by using `tsx`.

```
npx tsx your-code.ts
```

**Comment by rotemdan** [comment]
The library [couldn't be directly imported on Linux/macOS](#75), like in `import * from 'echogarden'` due to an incorrect case in the directory name of the `main` field in its `package.json` (the path used `API/API.js` instead of `api/API.js`. 

That was a long-lasting unreported issue, starting at the initial release on April 2023. For whatever reason, users were working around it without reporting it. That issue is now finally fixed. 

It's likely this issue was related to it, so I'm closing it as well.
