### ISSUE TITLE
"Error: No matching voice found" & "Error: No match found in uncrop timeline (should not occur)"

### ISSUE THREAD

**Issue by an-lee** [echogarden-project/echogarden#56]
I'm using echogarden in my product, a language learning tool.

Here is my use case.

### Step 1

I have a text:

```
In American English, the British ɑː sound is pronounced as æ. The most common example is the word ask. In British English, it's pronounced as /ɑːsk/, while in American English, it's pronounced as /æsk/.
```

### Step 2

Then I use OpenAI audio API to convert it to audio.

[audio](https://storage.enjoy.bot/4bf6b25ed76bdb338580c49244dea7b6.mp3)

### Step 3

I use echogarden align API to force-align the text and the audio.

It throws an error:

```
Error: No matching voice found
```

I suppose the error is caused by the IPA in the original text. So I try a different approach.

### Step 4

I use Whisper to create a new transcript from the audio:

```
In American English, the British sound is pronounced as A. The most common example is the word "ask." In British English, it's pronounced as "ask." While in American English, it's pronounced as "sk."
```

### Step 5

I use echogarden align API to force-align the new transcript and the audio.

It throws an error:

```
Error: No match found in uncrop timeline (should not occur)
```

---

My question is:

How can I avoid the errors above?

Many thanks!

**Comment by rotemdan** [comment]
## First error

The `Error: No matching voice found` is caused due to the text language being recognized as `Khmer`. You can see that in the log messages:

```
No language specified. Detect language using reference text.. 102.6ms
Language detected: Khmer (km)
```

The language detector currently used by default (`tinyld`) can sometimes get confused by various characters. In this case the IPA characters seemed to have caused it to detect an [unrelated language spoken in Cambodia](https://en.wikipedia.org/wiki/Khmer_language). I've developed my language detector, that should be much more accurate, about a year ago but haven't deployed it yet.

To resolve that, for now, simply pass the language like `--language=english`.

## Second error

The second error was an edge case of the timeline uncropping processes that wasn't handled correctly. It happened because of rounding of some of the timestamps. I fixed it now. It will be added in the next release.

**Comment by an-lee** [comment]
Thanks for your quick reply.

I did miss the `Language detected: Khmer (km)` log.  Now I know how to handle this.
