### ISSUE TITLE
Attempted import error: 'alawmulaw' does not contain a default export (imported as 'AlawMulaw')

### ISSUE THREAD

**Issue by smoores-dev** [echogarden-project/echogarden#76]
Howdy!

I'm starting to make use of echogarden's VAD functionality for some super basic silence detection in Storyteller. It seems like the distributed files for echogarden attempt to import `'alawmulaw'` as a default export (which I suspect works fine in echogarden because of your `allowSyntheticDefaultImports` in your tsconfig.json?), despite it not actually _having_ a default export.

Unfortunately, webpack doesn't seem to be able to process this, and throws an error:

```
 ⨯ ../node_modules/echogarden/dist/audio/AudioBufferConversion.js
Attempted import error: 'alawmulaw' does not contain a default export (imported as 'AlawMulaw').

Import trace for requested module:
../node_modules/echogarden/dist/audio/AudioBufferConversion.js
../node_modules/echogarden/dist/denoising/RNNoise.js
../node_modules/echogarden/dist/api/VoiceActivityDetection.js
```

Would it be possible to update the `alawmulaw` import to use named exports?

**Comment by rotemdan** [comment]
I've set `"allowSyntheticDefaultImports": false` (the official TypeScript default is `true`) and there were multiple imports that failed: `onnxruntime-node`, `jieba-wasm`, `sam-js` and `json5`. 

`alawmulaw` was not one of them, though I could change it to use `*` import instead. That's also really easy.

The problem now is that I get TypeScript error about the using default export from `sam-js`, but actually, that's the only way that library can be imported. So `"allowSyntheticDefaultImports": false` effectively produces a misleading error message and breaks working code in this case. Anyway I worked around that by changing the type declaration of `sam-js`.

It's easy to change the import for `alawmulaw`, but why are you trying to use a bundler at all? This package is virtually impossible to run on the web (`onnxruntime-node` is a node-only package, using native bindings, it uses a package system that stores data on user directories, etc.). Maybe you're trying to bundle for other reasons? That's important information. Can you explain more?

The best approach, in the long term would be to modularize a lot of the built-in functionality to separate packages. Like what I'm doing now with `wave-codec` and other parts of the library. The separate packages are independent are designed to work on multiple JavaScript runtimes, including browsers, Deno and Bun. That is a long-term project, though, and would require testing each of these separated packages individually.

Anyway, I've actually completed a full rewrite of the functionality of `alawmulaw` in TypeScript few weeks ago, as part of process of splitting out the WAVE encoder/decoder to an independent package (will be named `@echogarden/wave-codec` when published). It will be completely removed as dependency once the rewrite is sufficiently tested (rewritten code got inspected by Claude 3.5 Sonnet and ChatGPT, but I'll need to do more empirical testing). The original code of that library is written in an old, badly styled, cryptic JavaScript. I didn't want to keep using it anyway.

Most of the VAD functions don't work that reliably, and I wouldn't recommend using them. The only one that's actually robust in practice is the one I wrote myself, called `adaptive-gate`, which is what is used by default on all operation. It's basically a noise gate that is band limited up to 1 kHz (speech frequencies). The rest of the engines frequently produce false positives, and may cut speech in places where it shouldn't.

**Comment by smoores-dev** [comment]
> I've set "allowSyntheticDefaultImports": false (the official TypeScript default is true) and there were multiple imports that failed: onnxruntime-node, jieba-wasm, sam-js and json5. ... alawmulaw was not one of them

It's very possible that I was wrong about the relationship here; just sort of surprised to see that Typescript wasn't upset about this in echogarden itself!

> It's easy to change the import for alawmulaw, but why are you trying to use a bundler at all?

Ha, great question. Storyteller is written with Next.js, and Next.js has the somewhat bizzaro behavior of _bundling server-side code_. You can tell it _not_ to bundle specific server-side packages, but the mechanism for doing that seemed to be somewhat broken in Next.js 14, and wasn't preventing it from attempting to bundle echogarden.

Since opening this issue, I actually updated to Next.js 15 for Storyteller and that allowed me to properly exclude echogarden from bundling, so I have a workaround here, and maybe it's not worth it to change any echogarden code to account for this issue.

I am actually using the `adaptive-gate` VAD function; it's perfect for what I'm using for, which is just guessing (based on silence length) where a sentence break is near a place that I'd like to split a long audio file. I ran a few tests and every time I was able to correctly identify a space between sentences by just finding the maximum length stretch of silence in a two-minute given range.

Definitely feel free to close this if you see it as not worth addressing!

**Comment by rotemdan** [comment]
At some point I'll publish `adaptive-gate` as an independent package like `@echograden/adaptive-gate` so it can be used on the web and other platforms (no reason why not - it's written in pure TypeScript). I actually haven't considered that, since I'm prioritizing larger components.

This whole modularization thing, while generally positive, also means that maintenance would become a bit more complex. Lots of shared dependencies or methods will need to either become duplicated code (generally something I'm trying to avoid at all costs), or be split out yet more small packages. Every package would have it's own `package.json`, `README`, etc. which makes the overhead of maintenance larger and more clumsy in practice (and sometimes error-prone).

There are a lot of benefits to the monolithic approach. Especially on early stages of development where things are changing rapidly. I'm mostly going to modularize the parts that are relatively stable, for now.

----

Anyway, I hope you're aware of #75, which made me really disappointed overall. I have no idea how you, and many others, managed to make use of a package that **didn't even import correctly** on Linux and macOS, and not even report that once to the developer. Not even as a side comment or hint. 

It's likely a part of the reason why the usage is so low compared to the amount of effort that went into it. Again **The import paths simply didn't work and no one told me about it** right from the very first publication on April 2023. 

90% of users, when they see that, will give up, or perceive it to be buggy/broken. If that's what you and others wanted - to keep the this obscure - you achieved that. I don't know what else to say. I personally stopped putting much expectations for user feedback a long ago. I have never promoted this anywhere (no reddit, no blogs, nothing), and doesn't look like any of the users did. I have no ideas how much GitHub "stars" it gets. I gave up on that long ago.

**Comment by smoores-dev** [comment]
Cool! I am definitely familiar with the woes of modular package publishing; it can introduce a lot of overhead for sure.

---

Re: #75, I actually was not aware of that issue! I wish I could have helped spot it earlier; it looks like for whatever reason, I've been doing deep imports into the specific modules that I need, e.g. `import { detectVoiceActivity } from "echogarden/dist/api/VoiceActivityDetection"`. I don't think that I ever wrote those import paths intentionally... possibly it is itself a symptom of that bug; VS Code maybe suggested it because it couldn't resolve the export properly? But because of it, I never even noticed that there was a typo in the echogarden config, and because everything was just working on my end, I didn't even notice the wonky import paths.

Keeping echogarden obscure is the last thing that I want; this library is _outstanding_, and I hope that I've made clear in my issue reports and interactions with you how grateful I am for the immense amount of work that you've put into it. If I haven't, that's absolutely on me, and I cannot apologize enough.

**Comment by rotemdan** [comment]
Thanks for the report. I've changed the imports to `*` imports wherever I could identify, though I'm not sure if it would make a great difference in practice. Maybe at some point I'll seriously start to consider this kind of bundling as something that should be supported, and I'll test it directly, but not right now.

Anyway, right now I'm mostly limiting development to bug fixes only, although I have like 6 new independent packages I've recently published, and that are ready to be integrated (you can see them on the [organization page](https://github.com/echogarden-project/) and my personal list of source repositories). I'm concerned the current user base is too small to be able to catch potential regressions, so will reduce the amount of large, sweeping changes for now.
