### ISSUE TITLE
The best solution to avoid hallucinations on echogarden with whisper.cpp is?

### ISSUE THREAD

**Issue by jc955** [echogarden-project/echogarden#79]
Hi, @rotemdan, Ask some questions

I have limited experience with Whisper. I have researched many solutions, such as extracting audio from videos with FFmpeg + VAD filtering for silence, noise, DTW, DTW-RA, etc...

So I found echogarden. Echogarden is great, it integrates many third-party libraries, but there are some I'm not too familiar with. I want to know the best way to combine echogarden with whisper.cpp to avoid hallucinations and achieve speech-to-text Precise Alignment.

I'd love to hear your thoughts? Thank you very much.

**Comment by rotemdan** [comment]
VAD filtering helps.

Echogarden applies VAD filtering by default for all recognition inputs.

If you want even stronger filtering of silence and non-speech content, including background music (even loud background music), you can apply the `--isolate` option, which would apply the MDX-net source separation model to the input to isolate the speech, and only then apply the VAD and recognition. That combination is likely one of the strongest forms of (reliable) VAD that's likely available.

MDX-net can be fast if it runs GPU enabled (on Windows DirectML will be used if possible, on Linux, you need to manually install CUDA Toolkit 12.x and cuDNN 9.x and set a `mdxNet.provider=cuda` - it's all included in the documentation).

The timing accuracy of default `whisper.cpp` is okay but isn't great. There is the `--enableDTW` option (`whisper.cpp`'s internal experimental `dtw` implementation), and it produces more accurate timestamps, but with a lag. The lag issue could be due to many reasons, and it's possible I'm one of the few people who analyzed it in detail since I have tools to precisely observe timing of the resulting timestamps, on a word by word level. It's possible that it could be improved, but it's all in C++ code that I don't know much about.

Highest accuracy timestamps on Whisper, is likely the one I developed (default `whisper` engine, with `whisper.timestampAccuracy` set to `high`), which uses the ONNX runtime. It's not as fast as `whisper.cpp`, and doesn't support beam search - meaning it's a bit more prone to hallucinations, but I added several different mechanisms to prevent it. It also suppresses token patterns like unnecessary punctuation like `- Text`, and tags like `[laughter]`, `[music]`, which can prevent some unnecessary text to be output. Also has a guided decoding mechanism to encourage more punctuation output.

My personal experiments with producing subtitles for actual videos, the integrated `whisper` engine, although slower on larger models, produces more usable subtitles, with better timing and punctuation. I tried `whisper.cpp` on many practical cases, but it doesn't have a similar level of internal tuning. The output it produces is closer to what the raw model produces. Also, I tried `whisper.cpp` grammars for suppression of various patterns, and they slow and hard to work with. The C++ implementation is pretty basic and unoptimized.

**Comment by rotemdan** [comment]
The ONNX Whisper port was likely better tested for timing alignment (due to the general goal and functionality of Echogarden, it's just a higher priority goal than on other projects like `whisper.cpp`), but it has a main disadvantage that it only uses a single "beam" for decoding, meaning it sometimes may stop decoding a part early even if it has additional speech (odd early, high-confidence prediction of the end tag by the model), or will get caught in repetition loops (though I added several mechanisms to prevent that).

It's possible that the vocal isolation would help avoid the repetition loops in the first place, but it still could happen in some cases.

---

### Support and usage of the library (a bit off-topic)

Thanks for suggesting about the sponsorship. I'd be happy to get support for this, but it would make more sense to consider that when the user base is larger, at least in what I consider "reasonable" level given the project size - a few thousands of active users, for the very list. 

Echograden is still mostly obscure, although could be used in many cases where currently other tools are used. 

For example, the [`piper` speech synthesis library](https://github.com/rhasspy/piper/), written in C++, has become popular and well-known, but is difficult to build and run on macOS and other systems, since it's based on binary distributions, and in general isn't very feature rich. 

On the other hand Echograden, for more than a year now, has supported all piper voices (independent JavaScript implementation, called the `vits` engine), in an easy to install way, with advanced features like improved heteronym disambiguation, improved pronunciation of numeric patterns and date, fine-grained timestamps (piper doesn't have timestamps at all, I believe), configurable pause times between sentences (pretty crucial feature, as I see), etc.

People just don't know about this. I have never promoted it myself. Not even suggested it once on a forum or a different GitHub repository. There is no website or blogs. I've never seen it mentioned or recommended on Reddit.

I guess I was hoping for more "organic", word-of-mouth style spread. Maybe I made it a kind of (ongoing) experiment. The "organic" aspect didn't seem to happen so far. I don't know.
