### ISSUE TITLE
Amazon voice recognition fails

### ISSUE THREAD

**Issue by Cyberax** [echogarden-project/echogarden#80]
It looks like Amazon's AWS STT API requires the full locale name (`en-US`), not just a two-letter code (`en`).

**Comment by rotemdan** [comment]
Thanks for the report. My trials with Google, Microsoft and Amazon cloud services, ended more than year ago. This means I cannot really test if those services are still working.

I can make the change to pass the longer language code, but I wouldn't be able to test it.

The Amazon Transcribe type information shows these are the supported language codes:

```ts
export declare const LanguageCode: {
	readonly AF_ZA: "af-ZA";
	readonly AR_AE: "ar-AE";
	readonly AR_SA: "ar-SA";
	readonly CA_ES: "ca-ES";
	readonly CS_CZ: "cs-CZ";
	readonly DA_DK: "da-DK";
	readonly DE_CH: "de-CH";
	readonly DE_DE: "de-DE";
	readonly EL_GR: "el-GR";
	readonly EN_AB: "en-AB";
	readonly EN_AU: "en-AU";
	readonly EN_GB: "en-GB";
	readonly EN_IE: "en-IE";
	readonly EN_IN: "en-IN";
	readonly EN_NZ: "en-NZ";
	readonly EN_US: "en-US";
	readonly EN_WL: "en-WL";
	readonly EN_ZA: "en-ZA";
	readonly ES_ES: "es-ES";
	readonly ES_US: "es-US";
	readonly EU_ES: "eu-ES";
	readonly FA_IR: "fa-IR";
	readonly FI_FI: "fi-FI";
	readonly FR_CA: "fr-CA";
	readonly FR_FR: "fr-FR";
	readonly GL_ES: "gl-ES";
	readonly HE_IL: "he-IL";
	readonly HI_IN: "hi-IN";
	readonly HR_HR: "hr-HR";
	readonly ID_ID: "id-ID";
	readonly IT_IT: "it-IT";
	readonly JA_JP: "ja-JP";
	readonly KO_KR: "ko-KR";
	readonly LV_LV: "lv-LV";
	readonly MS_MY: "ms-MY";
	readonly NL_NL: "nl-NL";
	readonly NO_NO: "no-NO";
	readonly PL_PL: "pl-PL";
	readonly PT_BR: "pt-BR";
	readonly PT_PT: "pt-PT";
	readonly RO_RO: "ro-RO";
	readonly RU_RU: "ru-RU";
	readonly SK_SK: "sk-SK";
	readonly SO_SO: "so-SO";
	readonly SR_RS: "sr-RS";
	readonly SV_SE: "sv-SE";
	readonly TH_TH: "th-TH";
	readonly TL_PH: "tl-PH";
	readonly UK_UA: "uk-UA";
	readonly VI_VN: "vi-VN";
	readonly ZH_CN: "zh-CN";
	readonly ZH_HK: "zh-HK";
	readonly ZH_TW: "zh-TW";
	readonly ZU_ZA: "zu-ZA";
};
```

I've made the change to pass the full language code in `v2.0.10`.

I couldn't test it though.

Currently it means it wouldn't work with speech language detection, since language detection produces short, two letter country codes (it doesn't detect dialects). Due to the low usage of this particular feature (Amazon Transcribe) I'm not sure if it's worth it to put the effort to transform those auto-detected language codes to longer ones. For example, transforming `en` to `en-US` by default. That can be done in the future though.

**Comment by rotemdan** [comment]
On `v2.0.11` and `v2.0.12` I added default dialects for the languages supported by Amazon Transcribe. Meaning that if `en` is passed, it will extend it to `en-US` by default. If `pt` is passed, it will extend it to `pt-BR` by default, etc. It will also verify the language code is supported using the language list from the Amazon package.

The change was not tested. You'll need to provide feedback so I can know if it's working correctly.

**Comment by Cyberax** [comment]
> The change was not tested. You'll need to provide feedback so I can know if it's working correctly.

Seems to be working! Thank you!
